ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'KZT';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'TJS';

ALTER TYPE "PaymentType" ADD VALUE IF NOT EXISTS 'TERMINAL';
ALTER TYPE "PaymentType" ADD VALUE IF NOT EXISTS 'CLICK';
ALTER TYPE "PaymentType" ADD VALUE IF NOT EXISTS 'PAYME';

ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "terminalRevenue" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "clickRevenue" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "paymeRevenue" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "acceptedByName" TEXT;
